# Aggiunge la label 'documentation' se vengono modificati file .md
documentation:
- '**/*.md'

# Aggiunge la label 'build' se vengono modificati i file del workflow o di configurazione CI
build:
- .github/**

# Aggiunge la label 'c++-source' se viene modificato il codice nella cartella Cpp
c++-source:
- 'Cpp/**'

# Aggiunge la label 'swift-source' se viene modificato il codice Swift
swift-source:
- 'Sources/**/*.swift'

# Aggiunge la label 'swift-tests' se vengono modificati i file dei test Swift
swift-tests:
- 'Tests/**/*.swift'
